apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: os-manifests
  namespace: argocd
spec:
  destination:
    namespace: os
    server: https://kubernetes.default.svc
  project: default
  source:
    path: examples/manifests
    repoURL: https://gitlab.sikademo.com/argocd/os.git
  syncPolicy:
    syncOptions:
      - CreateNamespace=true