apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: os-manifests2
  namespace: argocd
spec:
  destination:
    namespace: os2
    server: https://kubernetes.default.svc
  project: default
  source:
    path: examples/manifests
    repoURL: https://gitlab.sikademo.com/argocd/os.git
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: false