apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: os-helm-from-package
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: os3
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://helm.sikalabs.io
    chart: hello-world
    targetRevision: 0.9.0
    helm:
      valuesObject:
        replicas: 2
