apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: os-helm-from-git2
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: os2
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/sikalabs/helm-repo-sikalabs.git
    targetRevision: master
    path: repo/hello-world-0.9.0.tgz
    helm:
      releaseName: helm-from-git
      valuesObject:
        replicas: 3
        TEXT: "Hello ArgoCD Training"
        host: os2-hello.k8s.sikademo.com