apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: os-sync-hooks-example
  namespace: argocd
  annotations:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: os
  project: default
  source:
    path: examples/sync-hooks/apps
    repoURL: https://gitlab.sikademo.com/argocd/os.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
